<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>

<!-- Table Pagination Component -->
<div class="pagination">
    <ul class="pagination-list">
        <!-- Pagination links will be generated by JavaScript -->
    </ul>
</div>
